language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/GiterLab/urllib
  - go get github.com/tobyzxj/uuid
  - go get github.com/GiterLab/aliyun-sms-go-sdk/sms

script: 
  - cd sms
  - go test 