ding_ding_robot:
  robot_one: https://oapi.dingtalk.com/robot/send?access_token=f6d35e625ec61e88b58d77dc98d5ba7c1342349aa882892347b13fcba98c5530
database_mysql:
  url: 120.79.154.53
  port: 3306
  user: root
  passwd: 123456
  database: stock

  rurl: 120.79.154.53
  rport: 3306
  ruser: root
  rpasswd: 123456
  rdatabase: stock
redis:
  first:
    addr: 120.79.154.53:6989
    passwd: 123456
    index: 1
    exptime: 604800

monitor_stock:

git log --format='%aN' | sort -u | while read name; do echo -en "$name\t"; git log --after=“2019-04-27” --before=“2019-05-05” --author="$name" --pretty=tformat: --numstat | awk '{ add += $1; subs += $2; loc += $1 - $2 } END { printf "added lines: %s, removed lines: %s, total lines: %s\n", add, subs, loc }' -; done

