// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login_agent.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	login_agent.proto

It has these top-level messages:
	CGetUpperInfo
	SGetUpperInfo
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 获取上级代码信息
type CGetUpperInfo struct {
	Appid            *uint32 `protobuf:"varint,1,opt,name=Appid" json:"Appid,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,opt,name=Uid" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGetUpperInfo) Reset()                    { *m = CGetUpperInfo{} }
func (m *CGetUpperInfo) String() string            { return proto.CompactTextString(m) }
func (*CGetUpperInfo) ProtoMessage()               {}
func (*CGetUpperInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CGetUpperInfo) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGetUpperInfo) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

//  获取上级代码信息
type SGetUpperInfo struct {
	State            *uint32 `protobuf:"varint,1,opt,name=State" json:"State,omitempty"`
	Weixinno         *string `protobuf:"bytes,2,opt,name=Weixinno" json:"Weixinno,omitempty"`
	Upperid          *uint32 `protobuf:"varint,3,opt,name=Upperid" json:"Upperid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SGetUpperInfo) Reset()                    { *m = SGetUpperInfo{} }
func (m *SGetUpperInfo) String() string            { return proto.CompactTextString(m) }
func (*SGetUpperInfo) ProtoMessage()               {}
func (*SGetUpperInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SGetUpperInfo) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SGetUpperInfo) GetWeixinno() string {
	if m != nil && m.Weixinno != nil {
		return *m.Weixinno
	}
	return ""
}

func (m *SGetUpperInfo) GetUpperid() uint32 {
	if m != nil && m.Upperid != nil {
		return *m.Upperid
	}
	return 0
}

func init() {
	proto.RegisterType((*CGetUpperInfo)(nil), "protocol.CGetUpperInfo")
	proto.RegisterType((*SGetUpperInfo)(nil), "protocol.SGetUpperInfo")
}

func init() { proto.RegisterFile("login_agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xc9, 0x4f, 0xcf,
	0xcc, 0x8b, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xda, 0x5c, 0xbc, 0xce, 0xee, 0xa9, 0x25, 0xa1, 0x05, 0x05, 0xa9,
	0x45, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0xbc, 0x5c, 0xac, 0x8e, 0x05, 0x05, 0x99, 0x29, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xbc, 0x42, 0xdc, 0x5c, 0xcc, 0xa1, 0x99, 0x29, 0x12, 0x4c, 0x20, 0x8e, 0x92,
	0x23, 0x17, 0x6f, 0x30, 0xba, 0xe2, 0xe0, 0x92, 0xc4, 0x92, 0x54, 0xa8, 0x62, 0x01, 0x2e, 0x8e,
	0xf0, 0xd4, 0xcc, 0x8a, 0xcc, 0xbc, 0xbc, 0x7c, 0xb0, 0x0e, 0x4e, 0x21, 0x7e, 0x2e, 0x76, 0xb0,
	0xea, 0xcc, 0x14, 0x09, 0x66, 0x90, 0x12, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x67, 0xe7,
	0x1b, 0x8d, 0x00, 0x00, 0x00,
}
